In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('computer.csv')
df

        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31...40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [3]:
df['age'] = df['age'].str.replace('31...40','31-0')
df

     age  income student credit_rating buys_computer
0   <=30    high      no          fair            no
1   <=30    high      no     excellent            no
2   31-0    high      no          fair           yes
3    >40  medium      no          fair           yes
4    >40     low     yes          fair           yes
5    >40     low     yes     excellent            no
6   31-0     low     yes     excellent           yes
7   <=30  medium      no          fair            no
8   <=30     low     yes          fair           yes
9    >40  medium     yes          fair           yes
10  <=30  medium     yes     excellent           yes
11  31-0  medium      no     excellent           yes
12  31-0    high     yes          fair           yes
13   >40  medium      no     excellent            no

In [7]:
x = df.iloc[:,0:4]
y=df['buys_computer']
x

     age  income student credit_rating
0   <=30    high      no          fair
1   <=30    high      no     excellent
2   31-0    high      no          fair
3    >40  medium      no          fair
4    >40     low     yes          fair
5    >40     low     yes     excellent
6   31-0     low     yes     excellent
7   <=30  medium      no          fair
8   <=30     low     yes          fair
9    >40  medium     yes          fair
10  <=30  medium     yes     excellent
11  31-0  medium      no     excellent
12  31-0    high     yes          fair
13   >40  medium      no     excellent

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
x,
y,
test_size=0.2,
random_state=1)

In [17]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

oe_age=OrdinalEncoder(categories=[['<=30','31-40','>40']])
oe_income=OrdinalEncoder(categories=[['low','medium','high']])
oe_credit=OrdinalEncoder(categories=[['fair','excilent']])

x_train['age']=oe_age.fit_transform(x_train[['age']])
x_train['income']=oe_income.fit_transform(x_train[['income']])
x_train['credit_rating']=oe_credit.fit_transform(x_train[['credit_rating']])

x_test['age']=oe_age.transform(x_test[['age']])
x_test['income']=oe_income.transform(x_test[['income']])
x_test['credit_rating']=oe_credit.transform(x_test[['credit_rating']])

ohe = OneHotEncoder(drop = 'if_binary',sparse_output=False)

x_train[['student_yes']]=ohe.fit_transform(x_train[['student']])
x_test[['student_yes']]=ohe.transform(x_test[['student']])

x_train=x_train.drop('student',axis=1)
x_test=x_test.drop('student',axis=1)

ValueError: Found unknown categories ['31-0'] in column 0 during fit